[build]
  command = "npm run docs:build"
  publish = "docs/.vitepress/dist"

[build.environment]
  NODE_VERSION = "24"

[context.branch-deploy]
  command = "npm run docs:build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200